name: Checks

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  template-packages-check:
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: set up weaver
      uses: open-telemetry/weaver/.github/actions/setup-weaver@3a3b7cc98e08f84bccda45c0f20522b51d64a88c # v0.23.0
    - name: verify template packages
      run: ./buildscripts/test_weaver_templates.sh
  policy-packages-check:
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: set up weaver
      uses: open-telemetry/weaver/.github/actions/setup-weaver@3a3b7cc98e08f84bccda45c0f20522b51d64a88c # v0.23.0
    - name: verify policy packages
      run: ./buildscripts/test_weaver_policies.sh
