name: Checks

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  template-packages-check:
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - name: set up weaver
      uses: open-telemetry/weaver/.github/actions/setup-weaver@adcf6fda79c3df1cb537669442aef753b7019777 # v0.24.2
    - name: verify template packages
      run: ./buildscripts/test_weaver_templates.sh
  policy-packages-check:
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - name: set up weaver
      uses: open-telemetry/weaver/.github/actions/setup-weaver@adcf6fda79c3df1cb537669442aef753b7019777 # v0.24.2
    - name: verify policy packages
      run: ./buildscripts/test_weaver_policies.sh
